### ISSUE TITLE
[2.0] Road to the 2.0 release

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-php#596]
I want to discuss how and when we will be releasing the 2.0 version of the SDK.

### Older suggestions
Those are the suggestions and ideas that I recovered from #424:

- [x] Switch to PSR-4 (#192, #414, #197)
- [x] Use Composer for autoloading (#211, #414, #197)
- [x] Drop PHP <5.6 support (#192, #197)
- [x] Improve documentation by adding docblocks where needed (PSR-5)
- [x] Refactor the processors system and introduce a ProcessorInterface interface (#472)
- [x] Use Httplug to not having the need to maintain the transport clients (#473, #537)
- [x] Improve how the options are passed to the client by using the OptionsResolver Component by Symfony (#462)
- [x] Refactor how the context of an event is gathered (#540, #569)
- [x] add scrutinizer to the project
- [x] use a code style

### Current status
The milestone has currently those open issues/PR:

- [x] #594: Drop the `trust_x_forwarded_proto` option enhancement
- [x] #592: Merge up to 1.9 
- [x] #584: Refactor the error and exception handlers 
- [ ] #563: Reject back-to-back duplicate errors/messages feature request
- [ ] #454: Serializer interface 

What we should do with them?

### Missing features

Do we have some major feature or refactor pending that would be a blocker for the release?

### Behavior

How should we handle the release? How should we handle support for the 1.x release?

I'll try to keep this first post updated.
Please reply with your opinions and suggestions. I'll do the same myself.

**Comment by Jean85** [comment]
Ok, now my personal suggestions:

### Current status
 * We should drop #563 from the milestone: it's a nice to have, but nobody has tackled that, I don't know how to do it and we can add it as a later new feature anyway
 * We should close #454; I've tried the same myself with #534 and failed, it seems to complicated IMHO; maybe just refactoring the tests should be enough, I'll try to do that

### Missing features
I don't know if we have any other missing pieces to fix, but I think we should leverage the new major version to change a two things, leveraging the PSR-4:
 * Move the namespace from `Raven` to `Sentry`
 * Flatten the dir from `lib/Raven/*` to simply `src/*`

### Behavior
For this, I think: 
 * we should suggest in the README **right now** that (major) new features should target the 2.0
 * Once the new version will be out, we should move the 1.x series to "security fixes only", no other support offered.

**Comment by Jean85** [comment]
@dcramer @stayallive @ste93cry @nokitakaze any input?

**Comment by nokitakaze** [comment]
> We should drop #563

I agree
> We should close #454

I agree
> we should move the 1.x series to "security fixes only"

As I can see, we can not even test this branch on PHP 5.3, 5.4, 5.5 now. So, yes

**Comment by dcramer** [comment]
I thought we already did #563? All you'd really need to do is stash the error type and error message and just check that when reporting the next one. You could also throw in the timestamp and expire the storage after N seconds.

**Comment by dcramer** [comment]
Also I'm ok with the rest of the proposal.

**Comment by Jean85** [comment]
> But I'm open also to leave it as is, just prepare the interface so that we can change the implementation later without BC

That seems a great strategy to me! :+1:

**Comment by ste93cry** [comment]
I believe we can close this issue since `2.0` landed as `beta` and all what was planned for the version has been done 🎉
