### ISSUE TITLE
[2.0] Port stuff from 1.x to 2.0

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-php#636]
We had a few PRs on master since the last realignment:

 - [x] #591: ported with #637
 - [x] #600: ported with #637
 - [x] #601: ported with #638
 - [x] #615: already ported with #616
 - [x] #617: ported with #637
 - [x] #621: ported with #637
 - [ ] #629: not sure if we should port it...
 - [ ] #630: ported with #639
 - [ ] #634: said we shouldn't port it? https://github.com/getsentry/sentry-php/pull/634#issuecomment-409219407
 - [x] #635: ported with #640
 - [x] #604: ported with #641

We must check if those need to be ported, and port them. I'll work on a few of those ASAP

**Comment by Jean85** [comment]
Closing this as completed, all issues where ported or discussed as "wont fix"
