### ISSUE TITLE
[2.0] Tracking issue - Unified API

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-php#670]
This is a non-exhaustive list containing todo's to refactor the current `2.0` branch to conform the unified SDK API see: https://docs.sentry.io/clientdev/unified-api/
In general, all points are up for discussion. This should be a rough guideline to hold on to while we progress through it.

- [x] Up minimum PHP version to 7.1 and use features (like: Return type declarations, nullable types, Throwable, …)
- [x] General wording changes to functions (e.g.: `leaveBreadcrumb` -> `addBreadcrumb`, `Config` -> `Options`)
- [x] Change Sentry protocol version to 7
- [x] Update SDK identifier + User Agent (`sentry.php`)
- [x] `Context` → `Scope`
- [x] Create `Hub` which takes some responsibility of the `Client` / `ClientBuilder`
- [x] Breakup Client
  - [x] Move `getLastEventID` to Hub
  - [x] Move breadcrumbs, context information into Scope
  - [x] Refactor `Middleware`'s to Integrations
  - [x] Remove some public setter/getter
  - [ ] ~~DSN → We no longer need `path` (`projectRoot`)~~ *Not important*
- [x] `shouldCapture` → `beforeSend`
- [x] Do not `setTags` in `Configuration`
- [x] `Stacktrace` should be `stacktrace.values[].frames`
- [x] `Breadcrumbs` should be `breadcrumbs.values[].crumb`
- [x] Remove base64 encoding
- [x] Remove `sanitization`
- [x] Remove docs from repo, they new live in https://github.com/getsentry/sentry-docs
- [ ] Write + Update Docs https://github.com/getsentry/sentry-php/issues/650

**Comment by HazAT** [comment]
Closing this in favor of https://github.com/getsentry/sentry-php/pull/677
